### ISSUE TITLE
makedirs error

### ISSUE THREAD

**Issue by badrulaiman53** [RaghavPrabhu/Deep-Learning#1]
Hello, I have tried many things as changing the directory and changing to my username but still no luck
![screenshot from 2019-03-07 19-58-31](https://user-images.githubusercontent.com/48338288/53999969-961a4980-4113-11e9-8aef-38a5b9afa1bb.png)

**Comment by tankienleong** [comment]
@badrulaiman53 use python3 should solve the problem.

**Comment by badrulaiman53** [comment]
thank you...it works..now I want to know what is the activation function used for the training?

**Comment by RaghavPrabhu** [comment]
> @badrulaiman53 use python3 should solve the problem.

I have updated the code in a simpler way. Please refer the Readme doc for commands
