### ISSUE TITLE
classify.py not working.What should be in sample_submission.csv

### ISSUE THREAD

**Issue by 1997827** [RaghavPrabhu/Deep-Learning#2]
Traceback (most recent call last):
  File "classify.py", line 92, in <module>
    main()
  File "classify.py", line 82, in main
    template_file = open('sample_submission.csv','r')
IOError: [Errno 2] No such file or directory: 'sample_submission.csv'

**Comment by tankienleong** [comment]
make sure you set the correct directory for sample_submission.csv
