### ISSUE TITLE
Executor failed to create kernel.

### ISSUE THREAD

**Issue by ghost** [RaghavPrabhu/Deep-Learning#3]
When running 'classify.py' I get the following error:

----------------------------------------------------------------------------------------------------------
 c:\l\tensorflow_1501918863922\work\tensorflow-1.2.1\tensorflow\core\common_runtime\executor.cc:644] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Mul, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Mul, conv/conv2d_params)]]
--------------------------------------------------------------------------------------------------------

Any ideas what is wrong.   Do I need to change the 'data_format'?  Something else?  Thanks!!

**Comment by RaghavPrabhu** [comment]
@FishForData , I have updated the code. Can you please pull the code and test?
